In [14]:
from numpy.linalg import *
import numpy as np

#A
A = np.array([[ 3,  2, -1], 
              [ 2, -2,  4], 
              [-1, .5, -1]])

b = np.array([1,-2,0])

Ainv = inv(A)

x = np.dot(Ainv,b)
solve_x = solve(A,b)
#反轉
print(Ainv)
#反轉相乘
print(x)
#程式解
print(solve_x)

[[ 1.48029737e-16 -5.00000000e-01 -2.00000000e+00]
 [ 6.66666667e-01  1.33333333e+00  4.66666667e+00]
 [ 3.33333333e-01  1.16666667e+00  3.33333333e+00]]
[ 1. -2. -2.]
[ 1. -2. -2.]
